//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecuperosYMandatos.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Textos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Textos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecuperosYMandatos.Recursos.Textos", typeof(Textos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identifíquese en nuestro sitio.
        /// </summary>
        public static string strIndex_I {
            get {
                return ResourceManager.GetString("strIndex_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si usted ya ha realizado el procedimiento de registración,.
        /// </summary>
        public static string strIndex_II {
            get {
                return ResourceManager.GetString("strIndex_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INGRESE AQUI.
        /// </summary>
        public static string strIndex_III {
            get {
                return ResourceManager.GetString("strIndex_III", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , para iniciar su sesión..
        /// </summary>
        public static string strIndex_IV {
            get {
                return ResourceManager.GetString("strIndex_IV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación.
        /// </summary>
        public static string strIndex_V {
            get {
                return ResourceManager.GetString("strIndex_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación....
        /// </summary>
        public static string strIndex_VI {
            get {
                return ResourceManager.GetString("strIndex_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        public static string strIndex_VII {
            get {
                return ResourceManager.GetString("strIndex_VII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En caso contrario, por favor ingrese su número de documento.
        /// </summary>
        public static string strIndex_VIII {
            get {
                return ResourceManager.GetString("strIndex_VIII", resourceCulture);
            }
        }
    }
}
